version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s Puma -p 3000 -b 0.0.0.0 -e production
    volumes:
      - .:/brimir
    ports:
      - '3000:3000'
    depends_on:
      - db
